USB: exynos_ss_udc: Add gadget ops set_wedge()
set_wedge() sets halt feature with the clear requests ignored.
If MSC class received unknown message, set_wedge() is called.

compliance CV test error:

ERROR: Invalid response, CSW should STALL
*************************
WARNING(5.2.2) Devices receiving a CBW with the wrong length should
stall further traffic on the Bulk In pipe, and either stall further traffic or
accept and discard further traffic on the Bulk Out pipe, until reset recovery.
If the device does not react in this manner, it should at least respond
correctly to a Reset Recovery.

Change-Id: I38fe14a0e03ecba34d9d55a5717cef0f4f9ec0b4
Signed-off-by: Yulgon Kim <yulgon.kim@samsung.com>